### ISSUE TITLE
To restart the touchpad does not work

### ISSUE THREAD

**Issue by ligomat** [vlasenko/hid-asus-dkms#18]
I apologize for my English but I'm Italian. I have a asus x556u, I followed the guide and the touchpad but it works to restart does not work and whenever I have to install the drivers from the terminal. I also had to download the file as .zip and then do it by the book because it does not make me add repository saying that is not valid. How can I fix?

**Comment by redmcg** [comment]
@ligomat Thanks for the report.

Could you please copy and paste the error you are seeing when adding the repository?

**Comment by ligomat** [comment]
@redmcg  the error:
`Cloning into 'hid-asus-fte-dkms'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`

**Comment by redmcg** [comment]
Try using https instead:
`git clone https://github.com/vlasenko/hid-asus-fte-dkms.git`

**Comment by ligomat** [comment]
@redmcg  perfect, it works!! Thanks !!! :)

**Comment by redmcg** [comment]
Is the touchpad working after restart?

**Comment by larixer** [comment]
@ligomat In case of touchpad is not working after reboot, please try to update the driver from source, there were some relevant changes today:
https://github.com/vlasenko/hid-asus-dkms#user-content-updating-to-the-latest-driver-version

**Comment by larixer** [comment]
Closing this one because of no issue author activity. Please reopen this issue if you still have any problems with the driver.
