### ISSUE TITLE
Cannot install the latest version. 

### ISSUE THREAD

**Issue by ceejayrao** [vlasenko/hid-asus-dkms#21]
output of dkms-add.sh

Error! Could not find module source directory.
Directory: /usr/src/..-hid-asus-dkms does not exist.
Error! Could not find module source directory.
Directory: /usr/src/asus-1.0 does not exist.

However when I run dev-run.sh, the driver loads the touchpad starts working fine.

PS: I tried installing this driver on 4.4.14 and was not successful, hence I installed 4.8.10 kernel on Kubuntu 16.04 and its worked fine two days back, but now with the update, it gave the above error.

**Comment by redmcg** [comment]
Can you please try another `git pull` and try again. Thanks

**Comment by ceejayrao** [comment]
yep that fixed it. Thank you.

-- Jitendra.
