### ISSUE TITLE
Tap to click not working

### ISSUE THREAD

**Issue by singhriju** [vlasenko/hid-asus-dkms#29]
Hi,
I can't thank you enough for this driver. 
I just had a small issue, the `tap to click` and `two-finger-tap for right click` feature is not working. It would be great if this works as it would then solve the problem completely.

**Comment by larixer** [comment]
Hi,

We have seen a bunch of similar issues, all resolved now, maybe you could check solutions inside and report whether anything is relevant for your case?
https://github.com/vlasenko/hid-asus-dkms/issues?q=is%3Aissue+tap+to+click+is%3Aclosed

**Comment by redmcg** [comment]
I'll close this as this problem is usually related to the configuration of the Xorg Input driver - and as @vlasenko has already pointed out - there is already solutions posted.

Please do reopen if there does still appear to be a genuine issue with the TouchPad driver.
