### ISSUE TITLE
Disabling the touchpad

### ISSUE THREAD

**Issue by ilgare** [vlasenko/hid-asus-dkms#37]
I have this touchpad on my Asus TP200 SA.

(i) The function key which should disable the touchpad does not work.

(ii) This computer has a screen that can be fully flipped back, making it look like tablet. The expected behaviour is that the touchpad and keyboard are disabled when it is flipped about halfway around. Currently the keyboard is disabled but not the touchpad.

I am not sure if hid-asus-dkms is the driver responsible for handling these. If that is the case, I would be glad to test code on my computer to help you implement it. Thanks,

Ilgar

**Comment by redmcg** [comment]
Item (i) works on my laptop - but item (ii) does not (not even the keyboard is disabled).

But I suspect both of these features would be implemented by your X framework. The Touchpad driver is a very low level driver which is only responsible for:
1. passing physical events to user space; and
2. for power management.

It doesn't receive events from other hardware - such as, for example, the keyboard.

Unfortunately I'm not familiar with this part of the X framework - but maybe something like [this](http://askubuntu.com/questions/544910/disable-touchpad-via-fn-key-asus-laptop) will help you get started.

I'll close this as I unfortunately can't really help further.
