### ISSUE TITLE
I/O Error in ASUS X556UR

### ISSUE THREAD

**Issue by stevemann2705** [vlasenko/hid-asus-dkms#38]
![screenshot from 2017-01-07 23-44-31](https://cloud.githubusercontent.com/assets/19262185/21744005/926ccfc2-d533-11e6-93c2-236b7800ce2c.png)

[Untitled Document.txt](https://github.com/vlasenko/hid-asus-dkms/files/691634/Untitled.Document.txt)

**Comment by ain101** [comment]
In the past "I/O error" was linked to issue  #24, which is fixed now.
Can you post dmesg output after boot.

**Comment by stevemann2705** [comment]
A silly reboot needed. This made me go mad. Working after reboot. Thanks.
