### ISSUE TITLE
Enable natural scrolling and tap to click

### ISSUE THREAD

**Issue by alejandrocarlos** [vlasenko/hid-asus-dkms#43]
Before anything else, thanks for your hard work and I truly appreciate your time to fix this issue for me.

I would like to request being able to enable natural scrolling and tap to click. Typically I would find those options in the Mouse and Touchpad setting but I can't seem to find them.

Thanks again for your hard work!

**Comment by larixer** [comment]
@alejandrocarlos This is unrelated to the driver. It is X server configuration issue. Example:
https://github.com/vlasenko/hid-asus-dkms/issues/27
