### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by larixer** [vlasenko/hid-asus-dkms#5]
This is an issue related to future inclusion of this source code to Linux kernel tree.

Right now in the source code it is mostly named FocalTech. I think it's not quite right. Because Vendor ID is ASUS. The firmware that implements Microsoft HID over I2C with vendor extensions has ASUS vendor id in HID descriptor. So I would call this TouchPad asus everywhere, or maybe asus_fte to not confuse it with devices that implement FocalTech I2C protocol, which is not HID protocol:
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiq-tjBha_QAhWHmBoKHWMBDlwQFggZMAA&url=http%3A%2F%2Fwww.newhavendisplay.com%2Fapp_notes%2FFT5x06_registers.pdf&usg=AFQjCNGfDLAi9Vg9oQBPUMxGMVaVMlnSgg&sig2=eqREkI2ERTF9GgI-R3LksQ&bvm=bv.139138859,d.d2s

Thoughts?

**Comment by redmcg** [comment]
Agree 100%. I was just about to raise the same issue - so we're on exactly the same page.

I was going to go with the naming you are using i.e. 'asus-fte'. I'll change the driver name to be 'hid_asus_fte' and the function prefixes from 'focaltech_' to 'asus_'

**Comment by larixer** [comment]
Yep, cool! 

Thank you!

**Comment by redmcg** [comment]
I just made commit 7b5d66f28bad97239d5b49b5f1b60a28b3576a2d to address this.

**Comment by larixer** [comment]
Looks good! Thanks a lot!

Victor
