### ISSUE TITLE
Got some isssues

### ISSUE THREAD

**Issue by hashmune** [vlasenko/hid-asus-dkms#51]
Hello there, I really appreciate your work here it enables everything in my touch pad except now my right button works as same as the left button.

**Comment by larixer** [comment]
Hi @hashmune 

Thanks for using this driver and reporting issues.

Please try the solution from this issue:
https://github.com/vlasenko/hid-asus-dkms/issues/17

**Comment by hashmune** [comment]
Thank you for fast response, I'll definitely look into that 👍

**Comment by dchesunas** [comment]
This solution doesn't work after reboot. Do you have another?:)

**Comment by hashmune** [comment]
@dchesunas it worked for me though
