### ISSUE TITLE
Driver Does Not Work

### ISSUE THREAD

**Issue by kah0922** [vlasenko/hid-asus-dkms#7]
I have an ASUS X540LA running the lastest openSUSE Tumbleweed. I installed the driver, but my touchpad is still recognized as a mouse.

**Comment by kah0922** [comment]
Wait, never mind. Didn't blacklist hic_generic. It's working now.

**Comment by redmcg** [comment]
Glad to hear it's working. But you shouldn't need to blacklist `hid_generic` (and you might need it if you plug in a USB mouse for example). The new driver should be picked up if it is in your initrd.

I'm not 100% sure how to add it to initrd in openSUSE - but for Ubuntu you need to edit `/etc/initramfs-tools/modules` and add a single entry of:
`hid_asus_fte`

And then rebuild your initrd with:
`update-initramfs -u`

It's up to you if you want to try this - but it would be good to have confirmation that this driver works in openSUSE without having to blacklist hid_generic.

**Comment by redmcg** [comment]
I should also point out that you can check the driver is in your initrd by running:
`lsinitramfs /boot/initrd.img-$(uname -r) | grep asus`
